using System.Diagnostics.CodeAnalysis;
using McMaster.Extensions.CommandLineUtils;

namespace Wolfgang.LogCompressor.Command;

/// <summary>
/// Parent <c>init</c> command that groups the configuration-file generators. It
/// produces nothing itself — the starter files are generated by the
/// <see cref="InitCompress"/> and <see cref="InitBundle"/> subcommands; invoking
/// <c>init</c> with no subcommand shows help.
/// </summary>
[Command
(
    Description = "Generate a starter configuration file",
    ResponseFileHandling = ResponseFileHandling.Disabled
)]
[Subcommand(typeof(InitCompress))]
[Subcommand(typeof(InitBundle))]
[ExcludeFromCodeCoverage]
internal class Init
{
    /// <summary>
    /// Shows help when no sub-command is specified.
    /// </summary>
    /// <param name="application">The command line application.</param>
    /// <returns>The exit code.</returns>
#pragma warning disable S2325 // Instance method by McMaster convention: CommandLineUtils resolves OnExecute via instance reflection — a static method is not discovered (verified: 'No method named OnExecute could be found').
    internal int OnExecute(CommandLineApplication application)
    {
        application.ShowHelp();
        return ExitCode.Success;
    }
#pragma warning restore S2325
}
